import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <header style={{ width: '100%', height: "50px", backgroundColor: 'gray' }}>HEY THIS IS A HEADER</header>
        <div style={{ height: "500px" }}>
          {children}
        </div>
        <footer style={{ width: '100%', height: "50px", backgroundColor: 'gray' }} >HEY THIS IS A FOOTER</footer>
      </body>
    </html>
  );
}
